### ISSUE TITLE
error: exponent has no digits

### ISSUE THREAD

**Issue by jiapei100** [Maratyszcza/FP16#4] opened 2018-07-06 10:32 UTC
Fail to build FP16, with the following ERROR messages:

I'm using Ubuntu 18.04, with GCC

```
$ gcc --version
gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```

[ 44%] Building CXX object deps/googletest/googlemock/gtest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
cd ....../FP16/build/deps/googletest/googlemock/gtest && /usr/bin/c++   -I....../FP16/deps/googletest/googletest/include -I....../FP16/deps/googletest/googletest  -fPIC -O3 -DNDEBUG   -fPIC -Wall -Wshadow -DGTEST_HAS_PTHREAD=1 -fexceptions -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -o CMakeFiles/gtest_main.dir/src/gtest_main.cc.o -c ....../FP16/deps/googletest/googletest/src/gtest_main.cc
In file included from ....../FP16/include/fp16.h:5:0,
                 from ....../FP16/bench/to-alt-array.cc:3:
....../FP16/include/fp16/fp16.h:155:26: error: exponent has no digits
  const float exp_scale = 0x1.0p-112f;
                          ^~~~~~
....../FP16/include/fp16/fp16.h:210:29: error: exponent has no digits
  const float scale_to_inf = 0x1.0p+112f;
                             ^~~~~~
....../FP16/include/fp16/fp16.h:211:30: error: exponent has no digits
  const float scale_to_zero = 0x1.0p-110f;
                              ^~~~~~
In file included from ....../FP16/bench/to-alt-array.cc:5:0:
....../FP16/include/fp16/psimd.h:21:46: error: exponent has no digits
  const psimd_f32 exp_scale = psimd_splat_f32(0x1.0p-112f);
                                              ^~~~~~
....../FP16/include/fp16/psimd.h:44:46: error: exponent has no digits
  const psimd_f32 exp_scale = psimd_splat_f32(0x1.0p-112f);
                                              ^~~~~~
....../FP16/include/fp16/psimd.h:80:48: error: exponent has no digits
  const psimd_f32 denorm_bias = psimd_splat_f32(0x1.0p-14f);
                                                ^~~~~~
In file included from ....../FP16/include/fp16.h:5:0,
                 from ....../FP16/bench/to-alt-array.cc:3:
....../FP16/include/fp16/fp16.h: In function ‘float fp16_ieee_to_fp32_value(uint16_t)’:
....../FP16/include/fp16/fp16.h:155:33: error: unable to find numeric literal operator ‘operator""f’
  const float exp_scale = 0x1.0p-112f;
                                 ^~~~
....../FP16/include/fp16/fp16.h:155:33: note: use -std=gnu++11 or -fext-numeric-literals to enable more built-in suffixes
....../FP16/include/fp16/fp16.h: In function ‘uint16_t fp16_ieee_from_fp32_value(float)’:
....../FP16/include/fp16/fp16.h:210:36: error: unable to find numeric literal operator ‘operator""f’
  const float scale_to_inf = 0x1.0p+112f;
                                    ^~~~
....../FP16/include/fp16/fp16.h:210:36: note: use -std=gnu++11 or -fext-numeric-literals to enable more built-in suffixes
....../FP16/include/fp16/fp16.h:211:37: error: unable to find numeric literal operator ‘operator""f’
  const float scale_to_zero = 0x1.0p-110f;
                                     ^~~~
....../FP16/include/fp16/fp16.h:211:37: note: use -std=gnu++11 or -fext-numeric-literals to enable more built-in suffixes
In file included from ....../FP16/bench/to-alt-array.cc:5:0:
....../FP16/include/fp16/psimd.h: In function ‘psimd_f32 fp16_ieee_to_fp32_psimd(psimd_u16)’:
....../FP16/include/fp16/psimd.h:21:53: error: unable to find numeric literal operator ‘operator""f’
  const psimd_f32 exp_scale = psimd_splat_f32(0x1.0p-112f);
                                                     ^~~~
....../FP16/include/fp16/psimd.h:21:53: note: use -std=gnu++11 or -fext-numeric-literals to enable more built-in suffixes
....../FP16/include/fp16/psimd.h: In function ‘psimd_f32x2 fp16_ieee_to_fp32x2_psimd(psimd_u16)’:
....../FP16/include/fp16/psimd.h:44:53: error: unable to find numeric literal operator ‘operator""f’
  const psimd_f32 exp_scale = psimd_splat_f32(0x1.0p-112f);
                                                     ^~~~
....../FP16/include/fp16/psimd.h:44:53: note: use -std=gnu++11 or -fext-numeric-literals to enable more built-in suffixes
....../FP16/include/fp16/psimd.h: In function ‘psimd_f32 fp16_alt_to_fp32_psimd(psimd_u16)’:
....../FP16/include/fp16/psimd.h:80:55: error: unable to find numeric literal operator ‘operator""f’
  const psimd_f32 denorm_bias = psimd_splat_f32(0x1.0p-14f);
                                                       ^~~
....../FP16/include/fp16/psimd.h:80:55: note: use -std=gnu++11 or -fext-numeric-literals to enable more built-in suffixes
CMakeFiles/to-alt-array-bench.dir/build.make:65: recipe for target 'CMakeFiles/to-alt-array-bench.dir/bench/to-alt-array.cc.o' failed
make[2]: *** [CMakeFiles/to-alt-array-bench.dir/bench/to-alt-array.cc.o] Error 1
make[2]: Leaving directory '....../FP16/build'
CMakeFiles/Makefile2:70: recipe for target 'CMakeFiles/to-alt-array-bench.dir/all' failed
make[1]: *** [CMakeFiles/to-alt-array-bench.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

```

**Comment by Maratyszcza** [comment] 2018-07-08 21:24
The problem seems to be caused by hexadecimal floating-point literals, which are not a part of C++11 standard, but are supported by gcc/clang as compiler-specific extensions. Should be fixed in 4b37bd31c9cc1380ef9f205f7dd031efe0e847ab

**Closed by Maratyszcza** 2018-07-08 21:24 UTC
